"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _filing_row_analyzing from './filing-row-analyzing.bones.json'
import _filing_row_queued from './filing-row-queued.bones.json'
import _filings_analysis_progress from './filings-analysis-progress.bones.json'
import _company_analysis_panel from './company-analysis-panel.bones.json'
import _peers_comparison_panel from './peers-comparison-panel.bones.json'

configureBoneyard({"animate":"shimmer"})

registerBones({
  "filing-row-analyzing": _filing_row_analyzing,
  "filing-row-queued": _filing_row_queued,
  "filings-analysis-progress": _filings_analysis_progress,
  "company-analysis-panel": _company_analysis_panel,
  "peers-comparison-panel": _peers_comparison_panel,
})
